### ISSUE TITLE
unsupported parameter -kb

### ISSUE THREAD

**Issue by sebix** [openSUSE/unrar_wrapper#2]
`-kb` is for *keep broken*.

That seems to be the default behavior for unar.

**Comment by kstreitova** [comment]
I'm afraid that according to my tests it's not the default behaviour for unar.

I created a test rar archive that has two parts. When I extracted only the first part with "unrar x -kb" it was really partially extracted. Without "-kb" option it fails.

However if I extract it with unar, it's not partially extracted:

```
# ls
loremipsum.part01.rar
# unrar x loremipsum.part01.rar 

UNRAR 5.50 beta 4 freeware      Copyright (c) 1993-2017 Alexander Roshal

Extracting from loremipsum.part01.rar

Extracting  loremipsum.txt                                            95%
Cannot find volume loremipsum.part02.rar
loremipsum.txt       - checksum error
Total errors: 1

# ls
loremipsum.part01.rar
# unrar x -kb loremipsum.part01.rar 

UNRAR 5.50 beta 4 freeware      Copyright (c) 1993-2017 Alexander Roshal

Extracting from loremipsum.part01.rar

Extracting  loremipsum.txt                                            95%
Cannot find volume loremipsum.part02.rar
loremipsum.txt       - checksum error
Total errors: 1

# ls
loremipsum.part01.rar  loremipsum.txt
# rm -rf loremipsum.txt 
# unar loremipsum.part01.rar 
loremipsum.part01.rar: RAR 5
No files extracted.

# ls
loremipsum.part01.rar
```

**Comment by sebix** [comment]
That's really strange, for me it works. I get partially extracted files from incomplete archives.

```
> unar archive.part01.rar 
archive.part01.rar: RAR
  dir_in_archive/file_in_archive  (4692176524 B, corrupted)... Failed! (Error on decrunching)
Extraction to current directory failed! (1 file failed.)
ele@linux-ek7w:~/tmp> ls
archive.part01.rar
dir_in_archive
> unar --version
v1.10.1
```

**Comment by kstreitova** [comment]
Weird indeed. Probably it depends on properties of the archive (one possible difference that crosses my mind is that my loremipsum archive comes from WinRAR, not RAR).
Anyway, as we have a case when unar can't partially extract incomplete archive we shouldn't support `-kb` parameter as a default here.
